### ISSUE TITLE
Ensure N latest boxes to have checksum

### ISSUE THREAD

**Issue by sparkoo** [sparkoo/boxitory#16]
- new configuration option `box.checksum_ensure`
  - integer value
  - tells how many boxes must be returned with checksum, in descendent order by version. When checksums for that many boxes is not precalculated, they are calculated on demand. Other versions has checksum only in case these are precalculated, thus easy to get.
  - when precalculation is turned off, just N boxes have checksum calculated on demand
    - `1` means that latest version of box comes always with checksums, other versions just when already precalculated
    - `0` no on demand checksum calculations are done
  - default `1`

**Comment by sparkoo** [comment]
please add wiki description of the feature, then close the issue. Thanks!

**Comment by vtelensky** [comment]
Wiki has been updated.
