### ISSUE TITLE
Print date & time to version descriptions

### ISSUE THREAD

**Issue by sparkoo** [sparkoo/boxitory#39]
When timestamp is used as version, it can be used to print in description as it is useful information.
  * new configuration `boolean` property `box.version_as_timestamp`
  * when `true`, version should be transferred to readable date & time and print in description
  * when `false` (default), don't change current behavior
  * when description exists, datetime should be concatenated in front of the description with ` - ` as separator
  * use ISO8601 format (https://en.wikipedia.org/wiki/ISO_8601) in UTC e.g.: `2017-11-02T09:42:55Z`

example (version 1509628106 has it's own description. version 1507206191 has no description.):
```
...
"versions": [
    {
      "version": "1509628106",
      "description: "2017-11-02T13:08:26Z - This version already has this description",
      "providers": [...]
    }, {
      "version": "1507206191",
      "description: "2017-10-05T12:23:11Z",
      "providers": [...]
    }
  ]
...
```

**Comment by sparkoo** [comment]
when you have time, please write simple description to Wiki, then close this. Thanks!

**Comment by vtelensky** [comment]
Done
